### PR TITLE
(ci) Add linux-arm support

### PR DESCRIPTION
**Pull request by perlun**
Still WIP, will need to test that this builds and is installable (on Raspberry Pi 2) before merging.

This is work towards completing #241.

### CODE REVIEW

**Comment by perlun** [comment]
This actually seems to work quite nicely! :tada: After installing this using the `perlang-install` installer script, here's what it looks like:

```
[23:36:17] per@pi2:~/git/perlang/scripts (feature/add-arm-support) $ perlang -V
Perlang 0.1.0-dev.192 (built from git commit 49d4604) on .NET 6.0.1

  Number of detected (v)CPUs: 4
  Running in 64-bit mode: False
  Operating system info: Unix 4.9.35.7
```

Running some simple command in the REPL also works:

```
[23:36:20] per@pi2:~/git/perlang/scripts (feature/add-arm-support) $ perlang
Perlang Interactive REPL Console (0.1.0-dev.192, built from git commit 49d4604)
> 2 ** 10
1024
> quit
```

However, it's not in any way practically "usable" on this kind of hardware because of its slowness to start the interpreter (which is hopefully caused at least partially by generic .NET overhead and not just "our own" code being slow):

```
[23:36:30] per@pi2:~/git/perlang/scripts (feature/add-arm-support) $ time perlang -v
0.1.0-dev.192

real	0m1.203s
user	0m1.160s
sys	0m0.060s
```

By comparison, this is the amount of overhead when starting a (C-based) Python interpreter on the same hardware. Approximately 100 times faster:

```
[23:34:29] per@pi2:~/git/perlang/scripts (feature/add-arm-support) $ time python -V
Python 2.7.16

real	0m0.011s
user	0m0.010s
sys	0m0.000s
```

Anyway, let's get this merged now. Hopefully it'll be a bit faster on Raspberry Pi 3.

**Comment by slovdahl** [comment]
Tested on a Raspberry Pi 3+ Rev 1.3. I ran the timings multiple times to avoid any impact of a slow SD card.

```
$ ./perlang -V
Perlang 0.1.0-dev.192 (built from git commit 4bcbc24) on .NET 6.0.1

  Number of detected (v)CPUs: 4
  Running in 64-bit mode: False
  Operating system info: Unix 5.4.79.7
```

```
$ time ./perlang -v
0.1.0-dev.192

real	0m0.538s
user	0m0.471s
sys	0m0.032s
```

```
$ time python2.7 -V
Python 2.7.16

real	0m0.009s
user	0m0.001s
sys	0m0.009s
```

```
$ time python3 -V
Python 3.7.3

real	0m0.013s
user	0m0.013s
sys	0m0.001s
```

**Comment by slovdahl** [comment]
Raspberry Pi 4 Model B Rev 1.2:

```
$ cat /proc/cpuinfo
...

Hardware	: BCM2711
Revision	: c03111
Serial		: 10000000ed26e1b0
Model		: Raspberry Pi 4 Model B Rev 1.1

$ uname -a
Linux rpi4 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

```
$ ./perlang -V
Perlang 0.1.0-dev.192 (built from git commit 4bcbc24) on .NET 6.0.1

  Number of detected (v)CPUs: 4
  Running in 64-bit mode: False
  Operating system info: Unix 5.10.63.7
```

```
$ time ./perlang -v
0.1.0-dev.192

real	0m0.360s
user	0m0.259s
sys	0m0.052s
```

```
$ time python2.7 -V
Python 2.7.16

real	0m0.010s
user	0m0.000s
sys	0m0.010s
```

```
$ time python3 -V
Python 3.7.3

real	0m0.010s
user	0m0.009s
sys	0m0.000s
```

**Comment by perlun** [comment]
@slovdahl Thanks a lot! :pray:

Interesting that it indeed worked on RPi 4 as well. :slightly_smiling_face: I would have assumed that I needed to fix `linux-arm64` for that, but perhaps you're running a 32-bit Raspbian on that? (AFAIK, Raspberry Pi 64 supports `aarch64` but perhaps it's less commonly used it in practice.)

**Comment by slovdahl** [comment]
> Interesting that it indeed worked on RPi 4 as well. slightly_smiling_face I would have assumed that I needed to fix `linux-arm64` for that, but perhaps you're running a 32-bit Raspbian on that? (AFAIK, Raspberry Pi 64 supports `aarch64` but perhaps it's less commonly used it in practice.)

Correct. Raspbian is still a 32-bit distro :unamused: On another RPi 4, running 64-bit Ubuntu 20.04, I get this:

```
$ curl -sSL https://perlang.org/install.sh | sh

error: unsupported CPU type: aarch64
```

**Comment by perlun** [comment]
> Correct. Raspbian is still a 32-bit distro unamused On another RPi 4, running 64-bit Ubuntu 20.04, I get this:
> 
> ```
> $ curl -sSL https://perlang.org/install.sh | sh
> 
> error: unsupported CPU type: aarch64
> ```

Thanks. This has now been fixed in #243, so Perlang should now also be installable on  RPi 4 running in 64-bit mode.

**Pull request merged**
